version: '3.1'
services:
  kibana:
    image: kibana:7.8.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
    networks:
      - elk
networks:
    elk:
        external: true